# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9591257500733d503a43267d91f37134"
name = "AWDS"
handle = "awds"
application_url = "https://shopify-app-azure.vercel.app/"
[auth]
redirect_urls = [
  "https://shopify-app-azure.vercel.app/auth/callback",
]
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_locations,read_orders,read_products,write_inventory,write_orders,write_products"

[auth]
redirect_urls = [
  "https://shopify-app-azure.vercel.app//auth/callback",
  "https://shopify-app-azure.vercel.app//auth/shopify/callback",
  "https://shopify-app-azure.vercel.app//api/auth/callback"
]

[pos]
embedded = false
